spring.application.name=identit

spring.datasource.url=jdbc:postgresql://localhost:5432/crypto_db
spring.datasource.username=postgres
spring.datasource.password=PostgresCedy

# Configuration Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cedricandriamifidisoa23@gmail.com
spring.mail.password=qhna lttm nbir pxdl

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Logging pour le débogage
logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG
logging.level.javax.mail=DEBUG

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuration du serveur
server.port=8080

# Configuration DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s

# Configuration de sécurité
app.security.max-login-attempts=3

# Session configuration
app.session.timeout-minutes=10
app.session.cleanup-interval-minutes=10

# Nombre de chiffres du code 2FA
app.security.two-factor-code-length=6

# Configuration Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Configuration des informations de l'API
springdoc.info.title=API d'Authentification
springdoc.info.description=API REST pour la gestion de l'authentification avec 2FA
springdoc.info.version=1.0.0
springdoc.info.contact.name=Tojo1512
springdoc.info.contact.email=tojorakotoarimanana01@gmail.com

# Configuration des logs
logging.level.root=INFO
logging.level.com.remix.authAPI=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Configuration CORS (désactivée car on utilise un proxy)
#spring.mvc.cors.enabled=false
#spring.mvc.cors.allowed-origins=http://localhost:8081
#spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
#spring.mvc.cors.allowed-headers=*
#spring.mvc.cors.allow-credentials=true

# Permettre l'override des beans
spring.main.allow-bean-definition-overriding=true